export const CHART_LAYOUT = {
  MARGIN: {
    TOP: 24,
    RIGHT: 24,
    BOTTOM: 24,
    LEFT: 24,
  },
  ROW_HEIGHT: 28,
  MIN_BAR_WIDTH: 4,
  LABEL_OFFSET: 8,
  MIN_LABEL_POSITION: 16,
} as const;

export const CHART_STYLING = {
  YEAR_FONT_SIZE: 32,
  COUNTRY_FONT_SIZE: 13,
  VALUE_FONT_SIZE: 13,
  COUNTRY_FONT_WEIGHT: 600,
  VALUE_FONT_WEIGHT: 700,
  BORDER_RADIUS: 8,
  BAR_PADDING: 2,
  HIGHLIGHT_WIDTH_RATIO: 0.6,
  HIGHLIGHT_HEIGHT_RATIO: 0.33,
} as const;

export const CHART_TOP_COUNTRIES_BAR_LIMIT = 10;

export const EPS = 1;
